### ISSUE TITLE
1.14 support?

### ISSUE THREAD

**Issue by ghost** [greatman/craftconomy3#146]
I would like to use this plugin on my 1.14.4 skyblock server, but on curseforge it says 1.8/1.7.9 only.

**Comment by pavog** [comment]
@jpie726 Have you tried CraftConomy3 on 1.14.4? I don't think the plugin uses any functions that are not available in 1.14.4 except the custom events. I fixed this issue here: https://github.com/pavog/craftconomy3/issues/50 and released [a new version](https://github.com/pavog/craftconomy3/releases/tag/3.5.2) which should be compatible with 1.14.4.

**Comment by ghost** [comment]
no i havent, but i will check out yours
